version: "3"

services:
  app:
    image: test_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Установите пароль администратора
    depends_on:
      - prometheus